In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
20   57  Female  Average    School       Yes
27   69  Female     Poor        PG        No
25   57  Female     Good    School        No
0    30  Female  Average    School        No
17   22  Female     Poor        UG       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size = 0.2)

In [11]:
X_train

review education
38     Good    School
39     Poor        PG
18     Good    School
32  Average        UG
8   Average        UG
6      Good    School
1      Poor        UG
36     Good        UG
28     Poor    School
44  Average        UG
20  Average    School
31     Poor    School
10     Good        UG
4   Average        UG
17     Poor        UG
12     Poor    School
24  Average        PG
5   Average    School
7      Poor    School
15     Poor        UG
11     Good        UG
23     Good    School
14     Poor        PG
9      Good        UG
27     Poor        PG
43     Poor        PG
21  Average        PG
19     Poor        PG
33     Good        PG
41     Good        PG
46     Poor        PG
0   Average    School
49     Good        UG
37  Average        PG
16     Poor        UG
42     Good        PG
2      Good        PG
47     Good        PG
35     Poor    School
30  Average        UG

In [34]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Example data
X_train = [['Poor', 'School'], ['Average', 'UG'], ['Good', 'PG']]
X_test = [['Poor', 'School'], ['Average', 'UG'], ['Good', 'PG']]

# Convert to DataFrame with feature names
X_train = pd.DataFrame(X_train, columns=['review', 'education'])
X_test = pd.DataFrame(X_test, columns=['review', 'education'])

# Initialize OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

# Fit the encoder
oe.fit(X_train)

# Transform the data
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

print("Encoded X_train:")
print(X_train)
print("Encoded X_test:")
print(X_test)

Encoded X_train:
[[0. 0.]
 [1. 1.]
 [2. 2.]]
Encoded X_test:
[[0. 0.]
 [1. 1.]
 [2. 2.]]


In [35]:
X_train

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [36]:
X_test

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [37]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le = LabelEncoder()

In [40]:
le.fit(Y_train)

LabelEncoder()

In [41]:
le.classes_

array([0, 1])

In [42]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [43]:
Y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [44]:
Y_test

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0], dtype=int64)

In [45]:
df.head(40)

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No