In [42]:
import pickle
import numpy as np

In [46]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [47]:
# assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype = object).reshape(1, 7)

In [49]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [53]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1, 1))

C:\Users\Nadim Ansari\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [54]:
test_input_sex

array([[0., 1.]])

In [55]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

In [59]:
test_input_embarked

array([[0., 0., 1.]])

In [57]:
test_input_age = test_input[:, 2].reshape(1, 1)

In [58]:
test_input_age

array([[31.0]], dtype=object)

In [60]:
test_input_transformed = np.concatenate((test_input[:,[0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked), axis = 1)


In [61]:
test_input_transformed.shape

(1, 10)

In [62]:
clf.predict(test_input_transformed)

array([0], dtype=int64)